### ISSUE TITLE
'/usr/local/bin/node' could not be spawned. Is it installed and on your path?

### ISSUE THREAD

**Issue by lukejagodzinski** [foliveira/jscs-fixer#1]
Shouldn't it look for node installed with the Atom? I have two instances of node installed in two separate directories and none of them is `/usr/local/bin/node`. I would like to specify the path or it should automatically get it from the Atom. In Atom on Ubuntu it's localized in `/usr/share/atom/resources/app/apm/bin/node`

**Comment by foliveira** [comment]
Hi @jagi.

I'll have to take a look at this, since I'm under the impression that Atom latest versions are shipped with io.js instead of node (but maybe it has changed since I can't seem to find anything about it).

I'm thinking of moving this configuration to a settings screen (as many packages do) or at least try to find a way of programatically find where Atom's getting it's Node/io.js binary installed.

Thanks for reporting!

**Comment by foliveira** [comment]
Should work now, by invoking the `jscs` binary directly (present in the package node_modules folder)
